ForgeRock/forgerock-javascript-sdk

- .env.example
- CHANGELOG.md
- package.json
- src/oauth2-client/index.ts
- tests/e2e/bad-login.test.ts
- tests/e2e/basic-login.test.ts
- tests/e2e/config.ts
- tests/e2e/test-site/autoscript.js
- Fixes OAuth2Client so it obeys `realmPath` config
- Updated e2e tests to support realms
> Adds realm path support to OAuth2Client

- CHANGELOG.md
- package-lock.json
- package.json
- src/fr-auth/index.ts
Fixes a non-relative import in the `FRAuth` module.
> Fixes non-relative import

- src/fr-webauthn/helpers.ts
- src/index.ts
- src/shared/constants.ts
- src/util/deferred.ts
- src/util/http.ts
- src/util/nonce.ts
- src/util/pkce.ts
- src/util/realm.ts
- src/util/storage.ts
- src/util/strings.ts
- src/util/timeout.ts
- typedoc.json
- Fixed doc config to allow some utils to be documented
- Exported `Deferred` and `nonce`
- Replaced single-character parameter names
> Updates docs and expands exports

- CHANGELOG.md
- package-lock.json
- package.json
- src/fr-webauthn/helpers.ts
- src/index.ts
- src/shared/constants.ts
- src/util/deferred.ts
- src/util/http.ts
- src/util/nonce.ts
- src/util/pkce.ts
- src/util/realm.ts
- src/util/storage.ts
- src/util/strings.ts
- src/util/timeout.ts
- typedoc.json
- Exports `Deferred` and `nonce`
- Updates doc config to include missing modules
> Release 1.0.2

- src/auth/index.ts
- src/oauth2-client/index.ts
- src/session-manager/index.ts
- src/token-manager/index.ts
- src/util/url.test.ts
- src/util/url.ts
- tests/integration/fr-auth.test.ts
Replaced `url` and `querystring` with custom implementation.
> Replaces node dependencies

- CHANGELOG.md
- package-lock.json
- package.json
- src/util/url.ts
Fixes typo in `FRWebAuthn` method name
> Release 1.0.4

- CHANGELOG.md
- package-lock.json
- package.json
- src/auth/index.ts
- src/auth/interfaces.ts
- src/fr-auth/index.ts
- src/fr-webauthn/index.ts
- src/oauth2-client/index.ts
- src/shared/interfaces.ts
- src/token-storage/interfaces.ts
- src/util/pkce.ts
- src/util/url.ts
- Added support for additional authentication tree querystring parameters
> Release 1.0.5

- README.md
Nath spotted a missing step, and some of the longer links wrapped causing them to break.
> SDKS-263 Add missing NPM build step and fix broken wrapped links.

- src/fr-webauthn/index.ts
- src/fr-webauthn/interfaces.ts
Reverts ForgeRock/forgerock-javascript-sdk#46
> Revert "-acceptableCredentials changed to allowCredentials"

- src/auth/index.ts
- src/config/interfaces.ts
- src/oauth2-client/index.ts
- src/session-manager/index.ts
- src/util/middleware.mock.data.ts
- src/util/middleware.test.ts
- src/util/middleware.ts
- tests/e2e/app/request-middleware/autoscript.js
- tests/e2e/app/request-middleware/index.html
- tests/e2e/server/routes.auth.mjs
- tests/e2e/suites/basic-login.test.ts
- tests/e2e/suites/request-middleware.test.ts
Summary:
As an app developer I want an SDK that is flexible enough, so I can pass additional parameters, headers and other request options to the trees.
Details:
Using the "middleware" pattern commonly used with Express.js and the "reducer" pattern commonly. used with Redux, we are providing a way to intercept a request just before it is sent to the server and run a series of functions, each provided the request object, and action object and a next method.
Todos:
> Feature (request): add middleware to modify request object

- package-lock.json
- package.json
- src/fr-webauthn/examples/authenticate-script.mock.data.json
- src/fr-webauthn/examples/registration-json.mock.data.json
- src/fr-webauthn/examples/registration-script.mock.data.json
- src/fr-webauthn/helpers.ts
- src/fr-webauthn/index.ts
- src/fr-webauthn/interfaces.ts
- src/fr-webauthn/script-parser.test.ts
- src/fr-webauthn/script-parser.ts
- src/fr-webauthn/script-text.mock.data.ts
- tests/e2e/app/txn-auth-oauth/autoscript.js
- tests/e2e/app/webauthn/autoscript.js
- tests/e2e/app/webauthn/index.html
- tests/test-env.js
**Summary:**
The WebAuthn node with AM has a choice between a script-based or JSON-based callback structure. This PR addresses the missing script-based support.
> Feature (WebAuthn): adds script-based WebAuthn node feature

- src/config/interfaces.ts
- src/token-storage/index.ts
- src/token-storage/session-storage.ts
- tests/e2e/app/token-storage/autoscript.js
- tests/e2e/suites/token-storage.test.ts
Summary:
Add sessionStorage as option to token storage configuration.
> Feature (Token Storage): add sessionStorage to choices

- package.json
- src/http-client/http-client.test.ts
- src/http-client/index.ts
- src/http-client/util.ts
- tests/e2e/server/constants.mjs
- tests/e2e/server/routes.resource.mjs
Summary:
Made a few adjustments for handling IG different from REST implementation of Transactional Authorization.
> Fix (Txn Auth): adjust http-client for REST

- package-lock.json
- src/auth/index.ts
- src/auth/interfaces.ts
- src/config/enums.ts
- src/config/interfaces.ts
- src/fr-auth/index.ts
- src/http-client/http-client.test.ts
- src/http-client/index.ts
- src/oauth2-client/index.ts
- src/session-manager/index.ts
- src/util/middleware.mock.data.ts
- src/util/middleware.test.ts
- src/util/middleware.ts
- tests/e2e/app/basic-login/autoscript.js
- tests/e2e/app/oauth-login/autoscript.js
- tests/e2e/app/txn-auth-basic/autoscript.js
- tests/e2e/app/txn-auth-oauth/autoscript.js
- tests/e2e/suites/basic-login.test.ts
- tests/e2e/suites/oauth-login.test.ts
- tests/e2e/suites/txn-auth-basic.test.ts
Summary:
To handle the parameter of `noSession` in auth trees, we need to detect the completion, successful or not, without the return of an `idToken`. We also need to provide an action payload for app devs to distinguish between auth types and trees.
> Feature (auth/middleware): handle noSession and add action payload for auth

- src/fr-webauthn/script-parser.ts
- src/fr-webauthn/script-text.mock.data.ts
**Summary**:
Addressing a few bugs caught with WebAuthn.
> Feat (webauthn): add authenticatorAttachment & fix bug with multiple devices

- package-lock.json
- tests/e2e/app/authn-device-profile/autoscript.js
- tests/e2e/app/authn-platform/autoscript.js
- tests/e2e/env.config.ts
- tests/e2e/server/env.config.copy.mjs
- tests/e2e/server/routes.auth.mjs
- tests/e2e/suites/authn-device-profile.lc.test.ts
- tests/e2e/utilities/setup-and-go.ts
Summary: Modified e2e test cases to be able to run against live environment. 
To finish:
> Test (e2e): modified live-capable tests to run against real environment

- CHANGELOG.md
- package-lock.json
- src/fr-user/index.ts
- src/token-storage/indexed-db.ts
A few small changes to prepare for regression testing.
- Added some comments to document the reason for both session ending requests in logout
- Fixed a type error for an IndexedDB method
- Updated dependencies
- Ran all tests locally: unit, integration, e2e both mock and live are all green
- Update CHANGELOG
> Task (regression): prep codebase for regression testing

- README.md
This PR is to test the Jenkins PR build trigger and I confirmed it does trigger build and tests. 
It also adds a "build status" badge in the readme file.
> Try PR build trigger

- CHANGELOG.md
- package-lock.json
- package.json
- tests/e2e/app/authn-basic/index.html
- tests/e2e/app/authn-central-login/index.html
- tests/e2e/app/authn-device-profile/index.html
- tests/e2e/app/authn-no-session/index.html
- tests/e2e/app/authn-oauth/index.html
- tests/e2e/app/authn-platform/index.html
- tests/e2e/app/authn-second-factor/index.html
- tests/e2e/app/authn-social-login-am/index.html
- tests/e2e/app/authn-social-login-idm/index.html
- tests/e2e/app/authn-webauthn/index.html
- tests/e2e/app/authz-tree-basic/index.html
- tests/e2e/app/authz-tree-oauth/index.html
- tests/e2e/app/authz-txn-basic/index.html
- tests/e2e/app/authz-txn-oauth/index.html
- tests/e2e/app/config-custom-paths/index.html
- tests/e2e/app/config-request-middleware/index.html
- tests/e2e/app/config-token-storage/index.html
- tests/e2e/app/ie11/index.html
- tests/e2e/app/index.html
- tests/e2e/app/misc-callbacks/index.html
- tests/e2e/app/register-basic/index.html
- tests/e2e/utilities/setup-and-go.ts
- tests/jest.basic.config.js
- tests/jest.e2e.config.js
Notes:
- Updated CHANGELOG.md
- Updated test timers (20 to 60 seconds) as there were some occasional failures due to timeout
- Updated dependencies
- For those that use "dark mode", I added a "dark mode" for the e2e test pages for eye comfort
- Cleaned up some dependencies (removed unneeded package and script that required it)
- Added build and e2e tests back to `git push` hook
> Beta release 3.0.0-beta1

- src/token-manager/index.ts
- tests/e2e/app/authn-central-login/autoscript.js
**Summary:**
Remove the encoding and decoding of data, but preserve the additional e2e tests from this task.
> task (getTokens): revert encoding on stored data

- samples/central-login/index.html
Update the documentation in the sole place we have it, to push to use legacy over modern.
> Docs: legacy and modern update usage

- package-lock.json
- package.json
- samples/reactjs-todo/server/constants.mjs
- samples/reactjs-todo/server/index.mjs
- samples/reactjs-todo/server/routes.mjs
- tests/package.json
Wrapping a few things in a try-catch to better handle messaging when the `.env` file is missing or attributes don't have values.
> task (react-blog): improve error handling for missing files

- .github/workflows/develop.yml
- package-lock.json
Rename main.yml -> develop.yml so that the checks only run against develop.
Github action filenames map to branches.
> task(setup-initial-action): Playwright Action

- CONTRIBUTING.md
Adds a contributing.md file to the repo to outline how to contribute.
> docs(root): Sdks-1419/add contributing file

- .github/workflows/macos.yml
> task(fix-merge-agent): Run CI when merge happens correctly

- CHANGELOG.md
https://bugster.forgerock.org/jira/browse/SDKS-1516
Add changes to the changelog for release tag 3.2.0
> task(changelog): Update Changelog for Release

- packages/javascript-sdk/package-lock.json
- packages/javascript-sdk/src/util/middleware.ts
Rename the internal next call to something else so when we have to discuss it we have a clearer idea of what we are talking about 😆 
- [x ] This change requires a documentation update
https://github.com/ForgeCloud/sdks.github.io/pull/189
> task(sdk): Rename `next` function which is private API

- .github/workflows/macos.yml
- README.md
We used to have a readme badge status. This PR adds a badge status for
the latest develop run in CI
> docs(readme): Update badge status for Readme

- packages/javascript-sdk/package-lock.json
- packages/javascript-sdk/src/util/timeout.test.ts
- packages/javascript-sdk/src/util/timeout.ts
There was a zendesk ticket that came up about the withTimeout function
so i've added test cases and may have discovered a weird microtask issue
with promises being raced.
> test(timeout.ts): Add test cases for the withTimeout function

- .github/workflows/macos.yml
- package-lock.json
- package.json
There was a breaking of the CI build during a clean install. There were
packages I should have cleaned up previously and I didn't.
Additionally, I added engine fields to the package.json so we are always
on the correct versions and updated CI builds to be the same across
different stages
- [x ] Bug fix (non-breaking change which fixes an issue)
I've run this with ACT locally although ACT requires ubuntu. I narrowed down the problem to two things
1) We had multiple npm versions in CI (woops)
2) We had rougue dependencies we did not need that I must have lost track of
> task(CI): Fix CI error

- packages/javascript-sdk/src/http-client/index.ts
https://bugster.forgerock.org/jira/browse/SDKS-1617
Remove the try catch and immediately return the first request. We don't
want to downgrade the request
e2e's cover most cases. we've dropped regression for transactional auth as of this ticket.
- [] Code peer-reviewed.
> task(remove-try-catch): Remove try catch

- .github/workflows/macos.yml
Nx Cloud isn't installing correctly and until a patch is made we have to manually install nx cloud like so.
CI
> fix(pipeline): manually install Nx Cloud

- e2e/autoscript-apps/src/authn-central-login/autoscript.ts
- e2e/autoscript-suites/playwright.config.ts
Removing alert from catch block that was probably left over from a
debugging session
n/a
> tests(remove-alert): There was an alert in a test that shouldn't be

- README.md
Had a bad link in readme that is fixed here
> task(bad-link): Fix link in readme

- package.json
- samples/reactjs-todo/project.json
- samples/reactjs-todo/webpack.config.js
No Jira ticket for this one as it was a quick fix.
Running the React sample app resulted in two separate errors:
- Invalid project (Nx)
- Invalid host (Webpack devServer)
Running the Rreact sample command, `npm run start:reactjs-todo`, successfully starts up the applications and all functionality is restored.
> fix(react-sample): project and host error in react sample

- .github/workflows/create-release.yml
- .github/workflows/release.yml
https://bugster.forgerock.org/jira/browse/SDKS-1801 
This adds a workflow file which is run when we create a new release.
We still need to manually version and push tags, but when we create the
release it will run the steps to publish to npm and github packages (so
its reflected on our github page).
n/a 
Needs to be tested still and verified
> feature(automate-releases): Automate Release Process

- package-lock.json
- packages/javascript-sdk/package-lock.json
- packages/javascript-sdk/package.json
https://bugster.forgerock.org/jira/browse/SDKS-1801
Merge release of 3.3 into develop
> Release 3.3.0 origin -> develop

- CHANGELOG.md
> docs(changelog): Fix changelog

- .github/labeler.yml
- .github/workflows/macos.yml
add the labeler action to PRs to aid in release note generation
> feat(labeler): Add labels on PR automatically

- .github/workflows/macos.yml
event is now pull_request_target intead of pull_request
None
In CI..
> feature(ci): Fix event name for PR

- packages/javascript-sdk/src/fr-webauthn/script-parser.test.ts
- packages/javascript-sdk/src/fr-webauthn/script-text.mock.data.ts
N/A
a new string added and unit test to ensure the regex parsing still works for the new string that was introduced
- [none]
Added unit test to ensure parsing works
> tests(new-webauthn-string): Verify new webauthn string parses

- .github/workflows/macos.yml
https://bugster.forgerock.org/jira/browse/SDKS-1520
Adds slack notifications to a new channel #sdk-cicd
> feature(root): Notify sdk-cicd channel on PR

- .github/workflows/macos.yml
- .husky/commit-msg
- commitlint.config.js
- package-lock.json
- package.json
N/A
Linting and enforcing commit style helps generate automatic release
notes
> ci: Add commitlint to CI and husky

- .github/workflows/macos.yml
commit lint action only works on linux.
> ci: fix-ci-error

- .github/workflows/macos.yml
Reverts ForgeRock/forgerock-javascript-sdk#215
> Revert "ci: fix-ci-error"

- .github/workflows/macos.yml
I think you have to use a checkout action to commit lint correctly
> ci: fix-action-lint-again

- .github/workflows/macos.yml
- .husky/pre-commit
- .husky/pre-push
- package.json
Fix commitlint in CI pipeline and fix husky hooks
removing the failing part
> ci: fix-commitlint-ci & fix husky

- .github/workflows/macos.yml
- .github/workflows/ubuntu.yml
- wss-unified-agent.config
[n/a]
This adds white source to the develop pipeline merge and fixes the commitlint to run on pull_request event so it looks at the PR commit and not the develop commit
> feat: whitesource and commitlint

- .github/workflows/macos.yml
[n/a]
fix the develop ci now :()
> ci: fix-develop-ci

- .github/workflows/ci.yml
- .github/workflows/ubuntu.yml
whitesource action needs to run on linux
> ci: whitesource action only runs on linux

- wss-unified-agent.config
remove the project name in favor of token per the error we get when running ci
> ci: remove-project-token-whitesource

- .github/workflows/ubuntu.yml
Add a job context so that the user key for whitesource is available to be read from the env
> ci: wss-user-key

- commitlint.config.js
- e2e/autoscript-apps/src/authn-saml/autoscript.ts
- e2e/autoscript-apps/src/authn-saml/index.html
- e2e/autoscript-apps/src/index.html
- e2e/autoscript-apps/webpack.config.js
- e2e/autoscript-suites/src/suites/authn-saml.test.ts
- e2e/mock-api/src/app/constants.js
- e2e/mock-api/src/app/responses.js
- e2e/mock-api/src/app/routes.auth.js
- packages/javascript-sdk/src/fr-auth/index.ts
- feat(redirect): add SML related params to resume method
- test(autoscript-apps,autoscript-suites,mock-api): test-saml-support
https://bugster.forgerock.org/jira/browse/SDKS-1715
adds e2e test cases for saml support
e2e tests
- [] Demo to PO and team.
> feat(javascript-sdk): sdks-1715/native-saml-support

- README.md
- packages/javascript-sdk/README.md
when i changed the workflow names, it broke the status badges. This
fixes and adds the two workflows we want displayed
> docs: readme-update-status-badges

- packages/javascript-sdk/package-lock.json
- packages/javascript-sdk/package.json
release beta that includes saml code
> chore: 3.3.1-beta.0

- .github/workflows/merge.yml
had an error in the last pr that broke the merge pipeline /shrug
> ci: fix-ci

- .github/workflows/merge.yml
disable distributed execution for publishing
> ci: disable-distributed-execution

- .releaserc.json
.../semantic-release/blob/master/docs/usage/workflow-configuration.md#release-branches
explanation why this is happening
> ci: semantic-release-requires-master

- .github/workflows/merge.yml
Add write permission for contents....for whatever reason the github token isnt pushing
> ci: merge.yml

- package-lock.json
- package.json
adds the missing module for the release process
> ci: add-missing-module-for-release

- .github/workflows/merge.yml
- package.json
- ci: add-missing-module-for-release
- ci: semantic-release-more
> semantic release changes

- e2e/autoscript-apps/src/index.html
- e2e/autoscript-apps/src/umd-bundle-check/autoscript.ts
- e2e/autoscript-apps/src/umd-bundle-check/index.html
- e2e/autoscript-apps/tsconfig.app.json
- e2e/autoscript-apps/webpack.config.js
- e2e/autoscript-suites/src/suites/umd-bundle-check.test.ts
- packages/javascript-sdk/project.json
- packages/javascript-sdk/rollup.config.js
There was a report on zendesk regarding the umd bundle. I removed the rollup config in the last release, which changed the
namespace of the UMD build. This changes the name back and adds the
rollup config back for this purpose.
> feat(javascript-sdk): add-back-proper-namespace

- CHANGELOG.md
- package-lock.json
- packages/javascript-sdk/package-lock.json
- packages/javascript-sdk/package.json
> chore: v3.3.1

- .github/workflows/merge.yml
The workflow wasn't working properly because of two reasons.
The affected commands needs the npx cloud start I think.
The set-shas action is better than the last workflow success
concept I think, at least it sets the arguments
> ci: fix-nx-publish

- .github/workflows/merge.yml
> ci: merge-yml

- .github/workflows/merge.yml
add install steps to the merge pipeline
> ci: add-cloud-install-to-merge

- CHANGELOG.md
- packages/javascript-sdk/CHANGELOG.md
No ticket, was messaged in slack
remove the SAML bullet point because we don't have a full grasp of what
SAML features the SDK supports
- Docs change
> chore: remove-saml-from-changelog

- .github/workflows/destroy_preview.yml
had some mistakes, working on fixing the pipeline on destroy
> fix: fix-issues-in-destroy-actions

- .github/workflows/merge.yml
add steps to publish the beta tag, and latest release tag.
> ci: update-release-process

- packages/javascript-sdk/project.json
missing script for beta deploy publish
> ci: update-publish-to-beta

- .github/workflows/merge.yml
Basically this failed in CI because i had DTE enabled. This means that an agent process tried to pick up the version command but in the job before I kill all agents. Version does not need to be done with DTE because its only one package and its not a significant load. I disabled DTE in the job and removed the start-cloud process.
> ci:disable-dte-for-version

- .github/workflows/merge.yml
> ci: fix-release-set-author

- packages/javascript-sdk/project.json
and it continues...the base branch default was main. now it should push to "develop" for betas and master for non beta (which is dry run and not going to run because its commented out still while this is ironed out).
> ci: base-branch-for-push-on-release

- .github/workflows/merge.yml
- package.json
- packages/javascript-sdk/project.json
the release process fails the push step. unsure exactly why, but i've checked all the documentation and maybe i'll have to remove this step. will try one last time.
> fix(javascript-sdk): fix-release

- .github/workflows/preview.yml
- docker-compose.yml
- e2e/autoscript-apps/src/misc-callbacks/autoscript.ts
- e2e/autoscript-suites/src/suites/misc-callbacks.lc.test.ts
- e2e/mock-api/src/app/responses.js
- e2e/mock-api/src/app/routes.auth.js
- packages/javascript-sdk/src/auth/enums.ts
- packages/javascript-sdk/src/fr-auth/callbacks/factory.ts
- packages/javascript-sdk/src/fr-auth/callbacks/text-input-callback.test.ts
- packages/javascript-sdk/src/fr-auth/callbacks/text-input-callback.ts
- packages/javascript-sdk/src/index.ts
- samples/todo-api/Dockerfile
No Jira as it's an external contribution. Thanks, @jedieaston!
Add support for TextInputCallback. This PR replaces its original PR to properly run CI: https://github.com/ForgeRock/forgerock-javascript-sdk/pull/276.
Unit test and end-to-end test created. Will ask contributor to manually verify as well.
> feat(javascript-sdk): add support for TextInputCallback [external contribution]

- .github/workflows/merge.yml
long story short, we need a user to make commits, sign them and be allowed to push to protected branches in CI so that we can version and update the package.json. Luis is easiest to do this as he's an admin, and we don't need red tape of adding a bot user with liscenses.
> ci: add-luis-as-publisher

- .github/workflows/merge.yml
> fix: luis-email-fix

- samples/central-login/webpack.config.js
- samples/embedded-login/webpack.config.js
for some reason I was injecting recursively the index.html into itself.
this was just weird.
> fix: multiple-asset-error

- CHANGELOG.md
- packages/javascript-sdk/CHANGELOG.md
- packages/javascript-sdk/src/auth/index.ts
- packages/javascript-sdk/src/http-client/helpers.ts
- packages/javascript-sdk/src/oauth2-client/index.ts
- packages/javascript-sdk/src/session-manager/index.ts
https://bugster.forgerock.org/jira/browse/SDKS-2141
Manually ran tests, but the browser developer tools (Chrome) seem to auto-lowercase all headers. Firefox seems to auto-lowercase only some headers. I'm not sure how to perfectly valid this.
> fix(javascript-sdk): capitalize headers

- .github/workflows/ci.yml
- CHANGELOG.md
- packages/javascript-sdk/CHANGELOG.md
make changes to the root changelog and add version and date to the changelog in the `packages/javascript-sdk`
None - for release
This is for the changelog updates so we can merge develop and master
> chore: release-changelog

- README.md
it was asked that we link the root README license file section to where the file lives in the javascript-sdk package
> fix: license-file

- .github/workflows/merge.yml
- .whitesource
- e2e/autoscript-suites/playwright.config.ts
- e2e/autoscript-suites/project.json
- package-lock.json
- package.json
redo the e2e server using a new nx executor that better handles the spawning of multiple targets. remove devices from playwright config that aren't super useful. move #307 here.
> ci: whitesource-and-e2e

- .github/workflows/merge.yml
latest isn't a tag in github actions
> fix: wrong-version

- .github/workflows/merge.yml
forgot the v in the action workflow job
> fix: merge.yml

- .github/workflows/merge.yml
add git email to the release process to allow version to continue
> fix: release-process

- .github/workflows/merge.yml
> fix: release

- .github/workflows/merge.yml
adding ssh key to actions checkout, secret key is in secrets for the repo, public key is on my personal keys settings
> fix: release-ssh-key

- .github/workflows/merge.yml
need to add ssh key beyond just in actions.checkout
> fix: ssh-key-2

- packages/javascript-sdk/package.json
release process added beta version, and then failed because of two reasons. first the npm key was removed by me earlier in the day by accident, and then the second time the version was pushed and the job "re run" failed becaue the tip of the repo was ahead of the run.
> chore: remove-version

- packages/javascript-sdk/.releaserc.json
> fix semantic plugins

- packages/javascript-sdk/src/fr-auth/callbacks/attribute-input-callback.test.ts
- packages/javascript-sdk/src/fr-auth/callbacks/attribute-input-callback.ts
- packages/javascript-sdk/src/fr-auth/callbacks/validated-create-password-callback.test.ts
- packages/javascript-sdk/src/fr-auth/callbacks/validated-create-password-callback.ts
- packages/javascript-sdk/src/fr-auth/callbacks/validated-create-username-callback.test.ts
- packages/javascript-sdk/src/fr-auth/callbacks/validated-create-username-callback.ts
- samples/angular-todo/src/app/features/journey/password/password.component.ts
- samples/angular-todo/src/environments/environment.ts
- samples/reactjs-todo/client/components/journey/text.js
[Please link jira ticket here
](https://bugster.forgerock.org/jira/browse/SDKS-1963)
update failed policies so that the sdk parses the json inside of the array
- [x ] Bug fix (non-breaking change which fixes an issue)
verified in the react app locally and then verified in the test case (integration)
> fix(javascript-sdk): failed-policies-json

- packages/javascript-sdk/package.json
- samples/central-login/project.json
- samples/embedded-login/project.json
> Update export map

- .github/workflows/merge.yml
nx cloud disable on the build before release
> ci: fix-ci-cloud

- e2e/autoscript-apps/package.json
- e2e/autoscript-suites/package.json
- e2e/mock-api/package.json
- e2e/token-vault-app/package.json
- e2e/token-vault-proxy/package.json
- packages/javascript-sdk/package.json
- plugins/wait-for-api/package.json
- samples/angular-todo/package.json
- samples/reactjs-todo/package.json
- samples/todo-api/package.json
- shared/network/package.json
- shared/types/package.json
- shared/workers/package.json
update the version fields so that react and all apps have a version and are private if not to be published. default to 0.0.0
> build: update-version-fields

- package-lock.json
package-lock was outdated in last pr
> build: update-package-lock

- commitlint.config.js
- shared/network/package.json
- shared/types/package.json
- shared/workers/package.json
update private field so we dont try to publish shared packages
> build(shared-network): update-private-field

- package-lock.json
- packages/javascript-sdk/package.json
> build: update-packages

- packages/javascript-sdk/src/token-manager/index.test.ts
- packages/javascript-sdk/src/token-manager/index.ts
https://bugster.forgerock.org/jira/browse/SDKS-2570
TokenManager.get tokens when nothing is past in can break in module systems that are not downleveled to supply the default. this change adds a fix where we supply a default to the destructuring so that this doesn't occur
verified via unit test and i copied the dist from the javascript-sdk build and put it in the app where the bug was discovered with no downleveling and it worked.
> fix(javascript-sdk): get-tokens-default-destructure

- packages/javascript-sdk/package.json
update javascript-sdk to 4.1.2 for release
> chore: update-package-version

- packages/javascript-sdk/CHANGELOG.md
update the changelog with release notes
> chore(javascript-sdk): update-changelog

- packages/javascript-sdk/CHANGELOG.md
- packages/javascript-sdk/src/oauth2-client/index.ts
> changelog to master

- CHANGELOG.md
- package-lock.json
- packages/token-vault/CHANGELOG.md
- packages/token-vault/LICENSE
- packages/token-vault/package.json
- packages/token-vault/rollup.config.js
- samples/angular-todo/src/environments/environment.ts
update package.json and changelog for release of token vault
> chore(token-vault): update-metadata-for-release

- packages/javascript-sdk/CHANGELOG.md
missed a note in changelog for 4.0 release reported in #sdk slack
> docs(javascript-sdk): fix-changelog

- samples/angular-todo/src/app/features/journey/form/form.component.ts
https://bugster.forgerock.org/jira/browse/SDKS-2538
[Sample App] Create a social login sample app in SDK
**1) Local Log-in**
**STEPS TO TEST IT:**
- if not user, create a new user
- Click on Sign in
- Enter password and user, hit enter or click on Submit
- The page will check your credentials and, if successful, it will finish the log in flow.
- Go to Todo section
- create a new todo, should add it with no error
- Log out and log in, the previously todo should now appear on the list.
**2) Social-media log-in**
Pre- requisites: The social identity provider service must be created and configured for the tenant. For this case, google social provider has been added as social identity provider service for the tenant only, via Access Management. …
> feat(angular-todo): add support for social login

- e2e/mock-api/src/app/routes.auth.js
- e2e/token-vault-app/index.html
- e2e/token-vault-app/src/main.ts
- e2e/token-vault-proxy/src/main.ts
- e2e/token-vault-suites/project.json
- e2e/token-vault-suites/src/basic.test.ts
- packages/token-vault/README.md
- packages/token-vault/src/lib/proxy.ts
- shared/network/src/lib/network.utilities.test.ts
- shared/network/src/lib/network.utilities.ts
- shared/types/src/lib/config.types.ts
- shared/workers/src/lib/interceptor.test.ts
- shared/workers/src/lib/interceptor.ts
> Fix proxy origins check

- packages/javascript-sdk/src/index.ts
expose the LoggerFunctions type because a client could use that in their code to define the custom logger
> fix(javascript-sdk): expose-logger-functions-type

- packages/javascript-sdk/package.json
- packages/token-vault/package.json
update versions in token vault and sdk
> chore: update-versions

- package-lock.json
- packages/javascript-sdk/CHANGELOG.md
- packages/token-vault/CHANGELOG.md
> docs: update-changelogs

- e2e/autoscript-apps/src/authn-otp-reg/autoscript.ts
- e2e/autoscript-apps/src/authn-otp-reg/index.html
- e2e/autoscript-apps/src/index.html
- e2e/autoscript-apps/webpack.config.js
- e2e/autoscript-suites/src/suites/authn-otp-reg.test.ts
- e2e/mock-api/src/app/responses.js
- e2e/mock-api/src/app/routes.auth.js
- e2e/token-vault-suites/src/basic.test.ts
- packages/javascript-sdk/src/fr-qr-code/index.mock.data.ts
- packages/javascript-sdk/src/fr-qr-code/index.test.ts
- packages/javascript-sdk/src/fr-qr-code/index.ts
- packages/javascript-sdk/src/fr-webauthn/fr-webauthn.mock.data.ts
- packages/javascript-sdk/src/index.ts
[SDKS-251](https://bugster.forgerock.org/jira/browse/SDKS-251)
This PR adds a utility class for handling QR Code containing journey steps. The class includes the two methods:
```js
const isQRCode: boolean = FRQRCode.isQRCodeStep(step);
const data: { message: string, use: string, uri: string } = FRQRCode.getQRCodeData(step);
```
Feature is unit tested, has mock e2e test and manually tested.
> feat(javascript-sdk): add QR Code utility class

- e2e/mock-api/src/app/routes.resource.js
- samples/angular-todo/src/environments/environment.ts
- samples/todo-api/src/app/middleware.js
the api changed and no longer allows the introspect call to pass the query param token, it needs it in the post body
> fix(mock-api): fix-introspect-call

- samples/angular-todo/src/app/features/journey/form/form.component.html
- samples/reactjs-todo/client/components/icons/apple-icon.js
- samples/reactjs-todo/client/components/icons/google-icon.js
- samples/reactjs-todo/client/components/journey/form.js
- samples/reactjs-todo/client/components/journey/identity-provider.js
- samples/reactjs-todo/client/components/journey/journey-state.js
- samples/reactjs-todo/client/styles/_custom-styles.scss
https://bugster.forgerock.org/jira/browse/SDKS-2762
add social login for react todo sample app
> feat(reactjs-todo): add social login for react todo sample app

- samples/reactjs-todo/client/components/journey/kba.js
- samples/todo-api/src/app/middleware.js
https://bugster.forgerock.org/jira/browse/SDKS-2484
feat(reactjs-todo): fix bugs
> feat(reactjs-todo): fix bugs

- packages/javascript-sdk/CHANGELOG.md
- packages/javascript-sdk/package-lock.json
- packages/javascript-sdk/package.json
update for release the changelog and version
> docs(javascript-sdk): update-changelog-and-version

- .github/workflows/ci.yml
- .verdaccio/config.yml
- e2e/autoscript-suites/package.json
- e2e/autoscript-suites/tsconfig.spec.json
- e2e/mock-api/src/index.js
- package-lock.json
- packages/javascript-sdk/src/fr-recovery-codes/index.ts
- packages/javascript-sdk/src/fr-recovery-codes/recovery-codes.test.ts
- packages/javascript-sdk/src/fr-recovery-codes/script-parser.test.ts
- packages/javascript-sdk/src/fr-recovery-codes/script-parser.ts
- packages/javascript-sdk/src/fr-recovery-codes/script-text.mock.data.ts
- plugins/wait-for-api/tsconfig.lib.json
[Please link jira ticket here
](https://bugster.forgerock.org/jira/browse/SDKS-2536)
add a method which gets a device name from the script that is returned by am when assigning a device name to a webauthn device so we can display it when displaying recovery codes
feat
unit tests & used in LW
> feat(javascript-sdk): add-getdisplayname-to-recoverycodes

- e2e/autoscript-apps/src/authn-protect/autoscript.ts
- e2e/autoscript-apps/src/authn-protect/index.html
- e2e/autoscript-apps/src/index.html
- e2e/autoscript-apps/webpack.config.js
- e2e/autoscript-suites/src/suites/authn-protect.test.ts
- e2e/mock-api/src/app/responses.js
- e2e/mock-api/src/app/routes.auth.js
- package-lock.json
- package.json
- packages/javascript-sdk/src/auth/enums.ts
- packages/javascript-sdk/src/fr-auth/callbacks/factory.ts
- packages/javascript-sdk/src/fr-auth/callbacks/ping-protect-evaluation-callback.ts
- packages/javascript-sdk/src/fr-auth/callbacks/ping-protect-initialize-callback.ts
- packages/ping-protect/.eslintrc.json
- packages/ping-protect/README.md
- packages/ping-protect/package.json
- packages/ping-protect/project.json
- packages/ping-protect/src/index.ts
- packages/ping-protect/src/lib/ping-protect.ts
- packages/ping-protect/src/lib/ping-signals-sdk.js
- packages/ping-protect/tsconfig.json
- packages/ping-protect/tsconfig.lib.json
- packages/ping-protect/tsconfig.spec.json
- packages/ping-protect/vite.config.ts
- tsconfig.base.json
- Create new module for Ping Protect
- Add Protect callback support
[Jira](https://bugster.forgerock.org/jira/browse/SDKS-2536)
This adds the Ping Protect feature to the ForgeRock JavaScript SDK.
This can be run against the Mock API for manual or automation. This can also be run against the Protect2 tenant.
> feat(ping-protect): new module for Ping Protect

- packages/javascript-sdk/src/auth/index.ts
- packages/javascript-sdk/src/auth/interfaces.ts
- packages/javascript-sdk/src/config/index.ts
- packages/javascript-sdk/src/config/interfaces.ts
- packages/javascript-sdk/src/fr-auth/index.ts
this is a hot fix. its not ideal due to file construction. This pr demonstrates a fix for the problem but I don't expect this to go in as is. We could support this but the step interface living in config is not great
> fix(javascript-sdk): circular-dependency

- e2e/autoscript-apps/src/authn-central-login/autoscript.ts
- e2e/autoscript-suites/src/suites/authn-central-login.test.ts
- e2e/mock-api/src/app/routes.auth.js
- package-lock.json
- packages/javascript-sdk/src/token-manager/index.ts
[Jira ticket](https://bugster.forgerock.org/jira/browse/SDKS-2945)
PKCE storage was conflicting with the configuration of sessionStorage for `tokenStore`.
Change WebStorage API key to a unique string.
Manual testing as well as additional automation.
Running the test server for manual verification, use this URL: https://sdkapp.example.com:8443/authn-central-login/?amUrl=https%3A%2F%2Fauth.example.com%3A9443%2Fam&clientId=WebOAuthClient&email=&middleware=&preAuthenticated=&pw=password&realmPath=root&resourceUrl=https%3A%2F%2Fapi.example.com%3A9443&scope=openid+profile+me.read&support=&tokenStore=sessionStorage&tree=&un=sdkuser&oauthThreshold=
> fix(javascript-sdk): sessionStorage conflict

- packages/javascript-sdk/src/index.ts
export stepoptions from index for public use
> feat(javascript-sdk): export-step-options-type

- packages/javascript-sdk/src/oauth2-client/index.ts
- packages/javascript-sdk/src/token-manager/index.ts
[Please link jira ticket here](https://bugster.forgerock.org/jira/browse/SDKS-2946)
Adding PingOne specific login error to allowed errors for Centralized Login.
Manually tested with PingOne tenant.
> fix(javascript-sdk): add PingOne login error to allowed errors

- CHANGELOG.md
- packages/javascript-sdk/CHANGELOG.md
- packages/javascript-sdk/package.json
- packages/javascript-sdk/src/fr-qr-code/index.ts
- packages/ping-protect/CHANGELOG.md
- packages/ping-protect/package.json
- packages/ping-protect/project.json
update versions and changelogs for release
> chore: release-work

- e2e/mock-api/src/app/responses.js
- package-lock.json
- packages/javascript-sdk/CHANGELOG.md
- packages/javascript-sdk/package.json
- packages/javascript-sdk/src/index.test.ts
- packages/javascript-sdk/src/index.ts
- packages/ping-protect/CHANGELOG.md
- packages/ping-protect/package.json
- packages/ping-protect/project.json
- packages/ping-protect/src/lib/ping-protect.test.ts
- packages/ping-protect/src/lib/ping-protect.ts
- packages/ping-protect/tsconfig.json
- packages/ping-protect/tsconfig.lib.json
dynamically import signals sdk in start of protect method
export fr-auth callbacks of protect in index
update changelog
> fix(javascript-sdk): fix-exports-update-protect

- e2e/autoscript-suites/src/suites/send-request-header.test.ts
- e2e/autoscript-suites/src/utilities/setup-and-go.ts
- packages/javascript-sdk/src/auth/index.ts
- packages/javascript-sdk/src/session-manager/index.ts
- packages/javascript-sdk/src/shared/constants.ts
- samples/angular-todo/README.md
- samples/reactjs-todo/README.md
Adds a new request header
https://bugster.forgerock.org/jira/browse/SDKS-3034
Adds a new request header
> feat: new request header

- package-lock.json
- package.json
- packages/ping-protect/package.json
- packages/ping-protect/tsconfig.json
- packages/ping-protect/vite.config.ts
update the module type in package.json
> fix(ping-protect): update-module-type

- e2e/autoscript-apps/src/authn-basic/autoscript.ts
- e2e/autoscript-suites/src/suites/authn-basic.lc.test.ts
- e2e/autoscript-suites/src/suites/send-request-header.test.ts
- e2e/autoscript-suites/src/utilities/setup-and-go.ts
- packages/javascript-sdk/src/auth/index.ts
- packages/javascript-sdk/src/config/index.ts
- packages/javascript-sdk/src/config/interfaces.ts
- packages/javascript-sdk/src/session-manager/index.ts
No Jira ticket as it was caught in testing, and is an immediate fix.
The addition of the new "platform" header can be breaking for those relying on CORS. The new header would have to be added, so we are converting the header to opt-in, instead of default.
Manually verified it, and automation passes.
> fix(javascript-sdk): change x-requested-platform to opt-in

- .prettierignore
- packages/ping-protect/src/lib/ping-signals-sdk.js
update signals sdk to latest to fix bug with extra html
> fix(ping-protect): update-signals-sdk

- packages/ping-protect/tsconfig.lib.json
the old esm module resolution would be fine if we wrote imports with .js at the end. we could use 'bundler' but then 'bundler' has odd
support of module types in package.json
Further node16 supports all of the above.
> build(ping-protect): update-module-resolution

- e2e/autoscript-apps/tsconfig.app.json
- e2e/mock-api/tsconfig.app.json
- package-lock.json
- packages/ping-protect/project.json
- packages/ping-protect/src/index.test.ts
- packages/ping-protect/tsconfig.lib.json
- packages/ping-protect/vite.config.ts
update bundle to leverage vite for now. then generate types with tsc.
https://github.com/ForgeRock/forgerock-javascript-sdk/assets/18267769/12bc67c0-1553-4a0e-be24-881cb257e41e
https://github.com/ForgeRock/forgerock-javascript-sdk/assets/18267769/ef23de90-8129-4de5-a0be-f6fe6a067b5e
https://github.com/ForgeRock/forgerock-javascript-sdk/assets/18267769/52d9249a-1208-40e8-9576-11769a20df19
> fix(ping-protect): bundling

- nx.json
- packages/ping-protect/project.json
- packages/ping-protect/src/lib/ping-signals-sdk.js
- tools/release/dev.mjs
> fix(ping-protect): update-ping-protect-signals-sdk

- packages/javascript-sdk/package.json
- packages/ping-protect/package.json
update versions in package.json
> chore(javascript-sdk): package-versions

- packages/javascript-sdk/CHANGELOG.md
- packages/ping-protect/CHANGELOG.md
> chore(javascript-sdk): changelogs

- package-lock.json
- packages/javascript-sdk/src/oauth2-client/index.ts
- packages/javascript-sdk/src/token-manager/index.ts
https://bugster.forgerock.org/jira/browse/SDKS-3250
adding the allowed error the the allowedErrors variable.
this will allow central login through ping fed
feat?/fix?
> feat: ping-fed-central-login

- e2e/autoscript-apps/index.html
- e2e/autoscript-apps/src/authn-recaptcha-enterprise/autoscript.ts
- e2e/autoscript-apps/src/authn-recaptcha-enterprise/index.html
- e2e/autoscript-suites/src/suites/authn-central-logout.test.ts
- e2e/mock-api/src/app/responses.js
- e2e/mock-api/src/app/routes.auth.js
- packages/javascript-sdk/src/auth/enums.ts
- packages/javascript-sdk/src/fr-auth/callbacks/factory.ts
- packages/javascript-sdk/src/fr-auth/callbacks/recaptcha-enterprise-callback.test.ts
- packages/javascript-sdk/src/fr-auth/callbacks/recaptcha-enterprise-callback.ts
- packages/javascript-sdk/src/index.ts
- packages/javascript-sdk/tsconfig.spec.json
(https://bugster.forgerock.org/jira/browse/SDKS-3212)
> Recaptcha enterprise

- e2e/autoscript-suites/package.json
- e2e/autoscript-suites/playwright.config.ts
- e2e/autoscript-suites/project.json
- e2e/token-vault-proxy/package.json
- e2e/token-vault-proxy/project.json
- e2e/token-vault-suites/playwright.config.ts
- nx.json
- package.json
- packages/javascript-sdk/package.json
- packages/ping-protect/package.json
- packages/token-vault/package.json
- pnpm-lock.yaml
- project.json
> chore: fix-deps

- e2e/autoscript-suites/project.json
- package.json
- packages/javascript-sdk/package.json
- packages/javascript-sdk/vite.config.ts
- packages/ping-protect/package.json
- pnpm-lock.yaml
add side effects array to the package.json for sdk&protect.
> chore: fix-side-effects

- packages/javascript-sdk/package.json
I accidentally deleted to export subpath
> chore: fix-subpath

- packages/javascript-sdk/src/oauth2-client/state-pkce.ts
- packages/javascript-sdk/src/token-manager/index.ts
> fix(javascript-sdk): change pkce utility to return storage function

- packages/javascript-sdk/CHANGELOG.md
- packages/javascript-sdk/package.json
- packages/ping-protect/CHANGELOG.md
- packages/ping-protect/package.json
> chore: update-changelogandpackage

- e2e/davinci-app/.eslintignore
- e2e/davinci-app/components/flow-link.ts
- e2e/davinci-app/main.ts
- e2e/davinci-app/package.json
- e2e/davinci-app/project.json
- package.json
- packages/davinci-client/src/lib/client.store.ts
- packages/davinci-client/src/lib/client.store.utils.ts
- packages/davinci-client/src/lib/collector.utils.ts
- packages/davinci-client/src/lib/config.slice.ts
- packages/davinci-client/src/lib/davinci.api.ts
- packages/davinci-client/src/lib/davinci.types.ts
- packages/davinci-client/src/lib/davinci.utils.ts
- packages/davinci-client/src/lib/mock-data/davinci.error.mock.ts
- packages/davinci-client/src/lib/node.reducer.ts
- packages/davinci-client/src/lib/node.slice.ts
- packages/davinci-client/src/lib/node.types.ts
- packages/davinci-client/src/types.ts
- pnpm-lock.yaml
[Jira ticket #3350](https://pingidentity.atlassian.net/browse/SDKS-3350)
This PR adds more granular error handing (differentiation between recoverable DaVinci flow errors and unrecoverable), it also adds selectors for easier state retrieval, and adds better typings all around to remove many of the `any` types from source code.
This also removes the `getState` from the DaVinci Client that returned the entire state object.
Exclusively tested via manual tests using a live PingOne tenant.
> feat(davinci-client): improve error handling, selectors and types

- packages/davinci-client/package.json
- packages/davinci-client/src/lib/authorize.utils.ts
- packages/davinci-client/tsconfig.lib.json
- pnpm-lock.yaml
> fix(davinci-client): fix-types

- packages/davinci-client/src/lib/authorize.utils.ts
[SDKS-3528](https://pingidentity.atlassian.net/browse/SDKS-3528)
Authorization URL options were not being stored. This adds the storage function call.
> fix(davinci-client): fix authorize util option storage

- .github/workflows/publish.yml
- .npmrc
- e2e/davinci-app/project.json
- packages/davinci-client/package.json
> chore: fix-command

- .github/workflows/publish.yml
- packages/javascript-sdk/package.json
- packages/token-vault/package.json
- pnpm-lock.yaml
> chore: pnpm worksaround

- packages/device-client/package.json
> chore: mark-private

- .github/workflows/publish.yml
> chore: stash-before-checkout-ci

- packages/davinci-client/src/lib/config.slice.test.ts
- packages/davinci-client/src/lib/config.slice.ts
https://pingidentity.atlassian.net/browse/SDKS-3515
if a trailing slash is not provided in the base-url, we should append one.
> fix(davinci-client): fix-trailing-slash

- .gitignore
- e2e/autoscript-suites/src/suites/authn-central-logout.test.ts
- package.json
- pnpm-lock.yaml
- project.json
Update infrastructure - no ticket.
> chore: update-nx

- .changeset/config.json
- .changeset/thin-tools-sing.md
- e2e/davinci-app/main.ts
- package.json
- packages/davinci-client/src/lib/config.types.ts
https://pingidentity.atlassian.net/browse/SDKS-3510 
use async config options instead of `ConfigOptions` type. Because we do not want a `baseUrl` in the `config` we should use the `AsyncConfigOptions` type so that it is required to pass in a well-known url for the package to derive a baseUrl from (or the paths/endpoints) to 
> fix(davinci-client): use-async-config-options

- .changeset/thick-squids-wink.md
- e2e/davinci-app/main.ts
- packages/davinci-client/package.json
- packages/davinci-client/src/index.ts
- packages/davinci-client/src/lib/authorize.utils.ts
- packages/davinci-client/src/lib/client.store.ts
- packages/davinci-client/src/lib/client.store.utils.ts
- packages/davinci-client/src/lib/collector.types.ts
- packages/davinci-client/src/lib/collector.utils.test.ts
- packages/davinci-client/src/lib/collector.utils.ts
- packages/davinci-client/src/lib/config.slice.test.ts
- packages/davinci-client/src/lib/config.slice.ts
- packages/davinci-client/src/lib/config.types.ts
- packages/davinci-client/src/lib/davinci.api.ts
- packages/davinci-client/src/lib/davinci.utils.test.ts
- packages/davinci-client/src/lib/davinci.utils.ts
- packages/davinci-client/src/lib/index.ts
- packages/davinci-client/src/lib/node.reducer.ts
- packages/davinci-client/src/lib/node.slice.ts
- packages/davinci-client/src/lib/node.types.ts
- packages/davinci-client/src/lib/wellknown.api.ts
- packages/davinci-client/src/lib/wellknown.types.ts
- packages/davinci-client/src/types.ts
https://pingidentity.atlassian.net/jira/software/c/projects/SDKS/boards/1234?selectedIssue=SDKS-3594
use wellknown endpoint to get endpoints available. Refactor of types
> fix(davinci-client): types-and-wellknown

- packages/davinci-client/README.md
- packages/davinci-client/src/lib/authorize.utils.ts
- packages/davinci-client/src/lib/node.types.ts
[Jira ticket SDKS-3385](https://pingidentity.atlassian.net/browse/SDKS-3385)
This is adding a first draft of a README.md with brief information regarding the DaVinci Client installation, API and how to use it.
No tests needed.
> docs(davinci-client): update readme.md with detailed information

- .changeset/config.json
the git url was wrong for ci changesets git hook
> chore: fix-changesets-git-url

- .github/workflows/publish.yml
fix the commit changesets make to pass commitlint
> chore: fix-ci-commmit

- .github/workflows/publish.yml
> chore: fix-repo-url

- .github/workflows/publish.yml
- .husky/install.mjs
- package.json
ignore husky in ci per husky docs.
> chore: husky-ci

- .gitignore
outputs aren't being ignored in ci, removed ./
> chore: ignore-outputs-again

- .husky/install.mjs
husky.install ist he api, the docs were wrong.
> chore: fix-husky-install

- .husky/install.mjs
- e2e/davinci-app/components/flow-link.ts
- e2e/davinci-app/components/password.ts
- e2e/davinci-app/components/protect.ts
- e2e/davinci-app/components/text.ts
- e2e/davinci-app/main.ts
- e2e/davinci-app/tsconfig.app.json
- package.json
- packages/davinci-client/src/lib/authorize.utils.ts
- packages/davinci-client/src/lib/client.store.ts
- packages/davinci-client/src/lib/client.store.utils.ts
- packages/davinci-client/src/lib/client.types.ts
- packages/davinci-client/src/lib/collector.types.ts
- packages/davinci-client/src/lib/collector.utils.test.ts
- packages/davinci-client/src/lib/collector.utils.ts
- packages/davinci-client/src/lib/config.slice.ts
- packages/davinci-client/src/lib/config.types.ts
- packages/davinci-client/src/lib/davinci.api.ts
- packages/davinci-client/src/lib/davinci.utils.test.ts
- packages/davinci-client/src/lib/davinci.utils.ts
- packages/davinci-client/src/lib/error.types.ts
- packages/davinci-client/src/lib/mock-data/node.next.mock.ts
- packages/davinci-client/src/lib/node.reducer.test.ts
- packages/davinci-client/src/lib/node.reducer.ts
- packages/davinci-client/src/lib/node.slice.test.ts
- packages/davinci-client/src/lib/node.slice.ts
- packages/davinci-client/src/lib/node.types.ts
- packages/davinci-client/src/types.ts
- packages/javascript-sdk/package.json
[Jira ticket: SDKS_3632](https://pingidentity.atlassian.net/browse/SDKS-3632)
Improve error handling and types.
General update for improved Dx and maintainability
> fix(davinci-client): improve typings and error handling

- e2e/davinci-app/project.json
- nx.json
- packages/davinci-client/src/lib/davinci.utils.ts
[Jira ticket: SDKS-3621](https://pingidentity.atlassian.net/browse/SDKS-3621)
Handle 302 redirect that results in CORS error. This can be attributed to incorrect Client IDs.
Manually tested by using incorrect Client ID within the test app's DaVinci configuration.
> fix(davinci-client): address invalid client id with 302

- .changeset/lemon-months-look.md
- packages/davinci-client/package.json
> chore: release-1.0

- CHANGELOG.md
> chore: add-davinci-client-changelog
