src/auth/index.ts
src/session-manager/index.ts
src/shared/constants.ts

Some AM endpoints require headers to be present when the CSRF filter is enabled.  This adds those headers to relevant endpoints.
https://backstage.forgerock.com/docs/am/6.5/dev-guide/#rest-CSRF

Fixes CSRF issues

---

src/auth/interfaces.ts
src/fr-auth/callbacks/index.ts
src/fr-auth/callbacks/kba-create-callback.ts

Callback properties `_id` and `input` are not always present.  This updates the interface to reflect that.

Makes some callback properties optional

---

src/fr-webauthn/index.ts

- Changed `getWebAuthStepType` to `getWebAuthnStepType`
- Simplified usage snippet

Fixes typo in FRWebAuthn method name and updates usage sample

---

src/auth/index.ts
src/auth/interfaces.ts
src/fr-auth/index.ts
src/oauth2-client/index.ts
src/shared/interfaces.ts
src/util/url.ts

One node type used for email verification during a "change password" tree leverages a querystring parameter named `suspendedId` to resume the tree when the user clicks a link in the verification email.
This change allows app developers to pass this and other name/value pairs to the SDK to be added to the constructed URL.

Adds ability to append querystring params to auth tree urls

---

README.md

This addresses an issue that was brought up the other day by aligning the `README.md` with the scripts in `package.json`.

Update README to reflect change in npm scripts

---

README.md

This will help surface our version history for those that leverage npm's website.

Docs: Add version history link to CHANGELOG.md

---

src/config/constants.ts

This increases the default timeout to 60 seconds, which will help in lower latency environments.

Feature: increase default timeout

---

src/fr-auth/callbacks/attribute-input-callback.ts
src/fr-auth/callbacks/index.ts
src/fr-auth/callbacks/validated-create-password-callback.test.ts
src/fr-auth/callbacks/validated-create-password-callback.ts
src/fr-auth/callbacks/validated-create-username-callback.test.ts
src/fr-auth/callbacks/validated-create-username-callback.ts
tests/e2e/app/authn-platform/autoscript.js
tests/e2e/server/responses.mjs
tests/e2e/server/routes.auth.mjs

**Summary**:
Update IDM callback handlers to handle proper type for `policies` property as well as a set method for the `validateOnly` property.
**Details**:
- Changed `policies` type from array to object
- Added `setValidateOnly` method to callbacks
- Added unit tests for IDM password and username callbacks
- Added step to e2e test for platform login that included validation only

Fix (IDM nodes): fix policies typing; add setValidateOnly method

---

src/fr-webauthn/index.ts
src/fr-webauthn/interfaces.ts
src/fr-webauthn/script-parser.test.ts
src/fr-webauthn/script-parser.ts
src/fr-webauthn/script-text.mock.data.ts

**Summary**:
AM conditionally sets a few key-value pairs for WebAuthn credential options object. When parsing the incoming callbacks, the SDK needed to align with conditions.
**Details**:
`relyingPartyId` and `allowCredentials` needed to be conditionally set in options object in order to avoiding DOM errors and continue iterating the AM trees.

Fix (webauthn): conditionally set key-value pairs options obj

---

CHANGELOG.md
README.md
package-lock.json
src/fr-webauthn/helpers.ts
src/fr-webauthn/index.ts
src/fr-webauthn/script-parser.test.ts
src/fr-webauthn/script-parser.ts
src/fr-webauthn/script-text.mock.data.ts

**Summary**:
WebAuthn and AM support the idea of "usernameless" capability with WebAuthn tech that supports the storing of the username with the authentication device. When logging in, the user can use the device alone without the need for username or password input.
**Details**:
- Ensure the property of `requireResidentKey` is passed to the key creation options on both JSON-based and script-based configuration
- Ensure `userHandle` from the credential outcome is passed to the key getter options on both JSON-based and script-based configuration
**Testing**:
To test this, the easiest way is to reuse the `tests/e2e/app/authn-webauthn` test page and `PasswordlessWebAuthn` (if not, you'll have to build two different trees):
1. Ensure `PasswordlessWebAuthn` tree is built similar to the picture …

Feat (webauthn): support usernameless login with username on device

---

CHANGELOG.md
package-lock.json
package.json
src/fr-auth/callbacks/attribute-input-callback.ts
src/fr-auth/callbacks/validated-create-password-callback.ts
src/fr-auth/callbacks/validated-create-username-callback.ts
src/oauth2-client/index.ts
src/token-manager/index.ts
src/util/nonce.ts
src/util/pkce.ts

**Summary**:
To improve the security of the PKCE flow, we are introducing a higher entropy verifier and state string generation. We are also deprecating the `nonce` utility and `getAuthorizeUrl` method in a future version.
**Details**:
1. Added deprecation message to `nonce` and `getAuthorizeUrl`, but left it in the API to ensure no breakage
2. Utilize stronger entropy in string generation for verifier and state for PKCE flow

Fix (oauth): improve the entropy of oauth; deprecate nonce

---

package-lock.json
src/fr-user/index.ts

**Summary**:
FRUser's logout method was not calling session logout due to Express not exposing that endpoint publicly, which calling it would result in an error. This just adds a simple check before making the call. 
**Details**:
- Check if `forgeblocks.com` (Express) is in the baseUrl in the config
- If Express is used, skip the session logout and just call the OAuth methods
- If not on Express, call session logout along with the OAuth methods

Fix (fruser): add SessionManager.logout back to method

---

samples/central-login/index.html
src/fr-device/sample-profile.json
src/oauth2-client/index.ts
src/token-manager/index.ts

Summary:
FireFox and Safari have slightly different error messages related to the redirect to the login page and CORS. Since these errors are expected and should result in a redirect, we needed to add a check for them in the flow.

fix (central-login): handle redirect errors with FF and Webkit

---

.gitignore
package.json
tests/jest.basic.config.js
tests/jest.e2e.config.js

* Added jest-juint reports, so that we can track results in Jenkins builds. 
**Note:** The reports are generated under `reports/${Date.now()}` directory so that we can run and preserve all reports (unit, integration and e2e...). Take a look [here](https://jenkins.petrov.ca/view/JS/job/JS-Core-SDK/40/testReport/) for an example test report after successful build.

[CI/CD] Junit reporter for jest tests

---

src/oauth2-client/index.ts
src/oauth2-client/interfaces.ts
tests/e2e/app/authn-basic/autoscript.js
tests/e2e/app/authn-central-login/autoscript.js
tests/e2e/app/authn-device-profile/autoscript.js
tests/e2e/app/authn-email-suspend/autoscript.js
tests/e2e/app/authn-no-session/autoscript.js
tests/e2e/app/authn-oauth/autoscript.js
tests/e2e/app/authn-platform/autoscript.js
tests/e2e/app/authn-second-factor/autoscript.js
tests/e2e/app/authn-webauthn/autoscript.js
tests/e2e/app/authz-tree-basic/autoscript.js
tests/e2e/app/authz-tree-oauth/autoscript.js
tests/e2e/app/authz-txn-basic/autoscript.js
tests/e2e/app/authz-txn-oauth/autoscript.js
tests/e2e/app/config-custom-paths/autoscript.js
tests/e2e/app/config-request-middleware/autoscript.js
tests/e2e/app/config-token-storage/autoscript.js
tests/e2e/app/ie11/index.js
tests/e2e/app/misc-callbacks/autoscript.js
tests/e2e/app/register-basic/autoscript.js
tests/e2e/server/routes.auth.mjs

**Summary:**
This allows for the usage of `acr_values` in order to specify a tree when calling the authorize endpoint.
**Details:**
Pass `query` object properties from the  `options` object in `getTokens` through to the authorize call as query parameters. This allows the use of ACR Values to be used to call specific trees.
**Notes:**
There are a lot of test file changes, but it's just the changing of fallback username and password values to align with the test automation's configuration object and its test users.
Relevant file changes to feature:
- https://github.com/ForgeRock/forgerock-javascript-sdk/pull/106/files#diff-92cd59f4227ad81ad8a7bddc61f9b5396662a6720247007d545ee1da7c7e0b1a
- https://github.com/ForgeRock/forgerock-javascript-sdk/pull/106/files#diff-253bb1127ccf96479910d15d3b8c63 …

Feat (acr_values/authorize): pass query properties through to authorize call

---

src/fr-auth/index.ts
tests/e2e/app/authn-social-login-idm/autoscript.js

**Summary**
This adds the needed support for Apple Sign In and its requirement for using a form POST, rather than a traditional GET redirect. This requires AM to support this form POST, and redirect back to the client web app.
**Details**
- Apple provider configuration requires AM to handle the form POST
- AM will process that form POST and encrypt and encode the data and do a GET redirect back to the client web app with the URL parameter of `form_post_entry`
- The SDK provides an existing `resume` that has been modified to include this `form_post_entry` along with the previously saved step and its `authId`

feat (social-login): support Apple Sign In

---

CHANGELOG.md
package-lock.json
src/fr-webauthn/enums.ts
src/fr-webauthn/helpers.ts
src/fr-webauthn/index.ts
src/fr-webauthn/script-parser.ts
tests/e2e/app/authn-webauthn/autoscript.js

**Summary**
Original implementation of WebAuthn just throw errors and left if up to the developer to handle them. This PR adds a more an enhancement to the error handling for the convenience of the developer.
**Details**
All errors have been standardized around the spec found here: https://heycam.github.io/webidl/#idl-DOMException-error-names. I've also tried to stay aligned with iOS and Android's error handling as well.
This implementation catches the error, formats it appropriately for injecting into the `hiddenCallback`, and then throws with that same error object. This is so the developer is made aware of the error, and she can handle it if wanted, but if she just wants to submit it as-is to AM, she can just call `next`.
**Example usage**
```js
try {
step = await …
```

task (webauthn): improve error handling

---

src/token-manager/index.ts
tests/e2e/app/authn-central-login/autoscript.js
tests/e2e/server/routes.auth.mjs
tests/e2e/suites/authn-central-login.test.ts

Summary:
Encode data before storing in `sessionStorage` when fully redirecting to `/authorize` URL.
Details:
- base64 encode before storage and after retrieval
- write e2e tests coverage for full redirect

task (getTokens): encode data before storage and redirect

---

.github/pull_request_template.md

Create a pull request template for future PR's.
https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/creating-a-pull-request-template-for-your-repository 
Documentation states that adding this file to the .github/ folder should make it so the template is used on PR's. I'm not sure if it would show up in this PR, or if we just have to hope that it shows up after its merged.
Feedback on what we want in this is welcome.
https://bugster.forgerock.org/jira/browse/SDKS-1416

(docs): Sdks-1416/create-pr-template

---

.github/workflows/release.yml

fixing #146 which just didn't trigger the workflow, adding option to manually trigger.
It appears that the workflow call that creates the release may just emit a "publish" event. So we are trying that. Worst case scenario is i just manually publish again.

fix(ci): add workflow dispatch option and trigger on publish instead

---

nx.json

the affected commands require the `version` target to be a cacheable
operation in the pipeline
https://nx.app/runs/bXFJ7UcofMQ to see it working

ci: nx-affected-fix

---

packages/javascript-sdk/src/fr-auth/callbacks/polling-wait-callback.ts

The comment for `PollingWaitCallback.getWaitTime()` is wrong (it returns the time in milliseconds, not seconds), so this PR fixes that.
I looked at the docs for the Android SDK, and [it says milliseconds](https://developer.forgerock.com/sdks/android/api-reference/forgerock-auth/org/forgerock/android/auth/callback/PollingWaitCallback.html), and then I looked at the response I got from ForgeRock when doing `advanceJourney`, and it was in milliseconds. 

Fixed comment for PollingWaitCallback.getWaitTime().

---

packages/javascript-sdk/src/fr-device/index.ts

The device metadata collection code does feature detection to see if it
is safe to use a certain browser API without a crash. However, many of
the checks fail if the object it is checking is undefined. This commit
fixes that, by ensuring the typeof the object !== "undefined" (which is
always safe).
It also replaces the two usages of `window.crypto` with `globalThis.crypto`,
as that will work in both the browser and Node.js (even though Node
isn't officially supported, I don't think it should fall over when it
provides the same API in a different place).
I ran the library with …

fix(javascript-sdk): fix-profile-object-checks

---

e2e/autoscript-apps/src/config-request-middleware/autoscript.ts
e2e/autoscript-suites/src/suites/authn-central-login.test.ts
e2e/autoscript-suites/src/suites/config-request-middleware.test.ts
packages/javascript-sdk/src/config/interfaces.ts
packages/javascript-sdk/src/token-manager/index.ts
packages/javascript-sdk/tests/integration/oauth2-client.test.ts

BREAKING CHANGE: remove the ability to use 'modern' as a means of making calls. fetch complicates the auth process too much for the value it provides. we've opted to remove this support property, automatically defaulting to the iframe.
https://bugster.forgerock.org/jira/browse/SDKS-2330
remove the support property and remove tests that test, the modern fetch call. 
e2e's and not using modern at all.

fix(javascript-sdk): remove-support-property

---

package-lock.json
packages/javascript-sdk/src/oauth2-client/index.ts
packages/javascript-sdk/src/oauth2-client/interfaces.ts
packages/javascript-sdk/src/token-manager/index.ts
packages/javascript-sdk/tests/integration/oauth2-client.test.ts

use the prompt=none query parameter.
https://bugster.forgerock.org/jira/browse/SDKS-2060
prompt none provides a better experience when errors occur in an iframe during /authorize

fix(javascript-sdk): use-prompt-none

---

.github/workflows/merge.yml
package-lock.json
package.json
packages/javascript-sdk/project.json
packages/javascript-sdk/src/token-manager/index.ts

https://bugster.forgerock.org/jira/browse/SDKS-2375
the options call is a GetTokens but the options we spread in should only be a ConfigOptions. so we can remove the types from the call that are not config options and pass them into authorization url creation

fix: correct code / type in  getTokens call

---

e2e/autoscript-apps/src/authn-webauthn-device-registration/autoscript.ts
e2e/autoscript-apps/src/authn-webauthn-device-registration/index.html
e2e/autoscript-apps/src/index.html
e2e/autoscript-apps/webpack.config.js
e2e/mock-api/package.json
e2e/mock-api/src/app/app.certs.js
package-lock.json
packages/javascript-sdk/project.json
packages/javascript-sdk/src/fr-webauthn/index.ts

https://bugster.forgerock.org/jira/browse/SDKS-2298 
make it so `register` accepts a parameter for registering a device name. An optional generic parameter that adds a device name to the registration step. This makes it so that `::${devicename}` is concated to the device string that is made from the outcome.
See the e2e example, which uses stoyans tenant 
```
const url = new URL(window.location.href);
const amUrl =
url.searchParams.get('amUrl') || 'https://openam-forgerrock-sdksteanant.forgeblocks.com/am/';
const realmPath = url.searchParams.get('realmPath') || 'alpha';
const un = url.searchParams.get('un') || 'ryan';
const pw = url.searchParams.get('pw') || 'Password1!';
const tree = url.searchParams.get('tree') || 'WebAuthn-Registration';
``` …

feat(javascript-sdk): register-device-name

---

e2e/token-vault-app/project.json
e2e/token-vault-app/vite.config.ts
e2e/token-vault-app/vite.interceptor.config.ts
nx.json
package.json
shared/workers/src/lib/worker.utilities.test.ts
shared/workers/src/lib/worker.utilities.ts

[SDKS-2494](https://bugster.forgerock.org/jira/browse/SDKS-2494)
Remove /sessions endpoint from interception as it is not associated with Access Token management and therefor should not be proxied through Token Vault.
Manually tested in test apps.

fix(token-vault): removing /sessions endpoint from interception

---

packages/token-vault/README.md

[SDKS-2550](https://bugster.forgerock.org/jira/browse/SDKS-2550)
Adding a README.md to the Token Vault project.
No testing needed, but has been reviewed by multiple people.

docs(token-vault): add readme

---

e2e/autoscript-apps/index.html
e2e/autoscript-apps/src/authn-central-logout/autoscript.ts
e2e/autoscript-apps/src/authn-central-logout/callback.html
e2e/autoscript-apps/src/authn-central-logout/index.html
e2e/autoscript-suites/src/suites/authn-central-logout.test.ts
e2e/autoscript-suites/src/utilities/setup-and-go.ts
package-lock.json
packages/javascript-sdk/src/config/index.ts
packages/javascript-sdk/src/config/interfaces.ts
packages/javascript-sdk/src/fr-user/index.ts
packages/javascript-sdk/src/oauth2-client/index.ts
packages/javascript-sdk/src/oauth2-client/interfaces.ts

https://bugster.forgerock.org/jira/browse/SDKS-3211
In order to support full, complete logout with OIDC on PingOne, including termination of session and removal of cookie in third-party context, logout redirect is required. This PR adds the redirect, but only in the condition a `logoutRedirectUri` is present in the `logout` options argument, or detection of PingOne endpoint of `/as/signoff` in `endSession` endpoint URL.
There's a "safety switch" that allows the deactivation of this logout redirect regardless of config or endpoint URL, and that's the function's options argument. If you pass in `redirect: false`, it will disable the redirect explicitly in the `endSession` method.
This is so, in the rare case we have an issue with endpoint naming schemes, there's a way to turn it off.
Please …

fix(javascript-sdk): add logout redirect for pingone

---

package-lock.json
packages/javascript-sdk/src/oauth2-client/state-pkce.ts
packages/javascript-sdk/src/token-manager/index.ts

[Jira SDKS-3183](https://bugster.forgerock.org/jira/browse/SDKS-3183)
This adjusts the internal logic of Token Manager and OAuthClient to provide a bit more reuse within the DaVinci client module. The main intention was to expose the generation and storing of the PKCE related values so that the DaVinci module could use them without the internally "knowing" how or where the values are stored.
This has been tested manually using standard testing with SDK journey apps as well as the DaVinci module's prototype. Automation all passes without any change to tests.

feat(javascript-sdk): refactor authorize URL utilities for DaVinci

---

.changeset/config.json
.github/workflows/publish.yml
package.json
packages/javascript-sdk/package.json
packages/ping-protect/package.json
packages/token-vault/package.json

Fix command

---

.github/pull_request_template.md
contributing_docs/git.md
contributing_docs/releases.md

added a `contributing-docs` folder. This is because the `docs` folder is `.gitignored` for `typedoc` builds.

docs: update-contributing-docs

---

.changeset/great-bobcats-fry.md
e2e/autoscript-apps/src/authn-webauthn/autoscript.ts
packages/javascript-sdk/src/fr-webauthn/index.ts

[SDKS-3473](https://pingidentity.atlassian.net/browse/SDKS-3473)
In order to display a more user-friendly name when saving a WebAuthn/Passkey device to an account, we prioritized displayName over userName for assignment to the `name` property of the WebAuthn options object. This avoids the display of UUIDs for saved credentials.

fix(javascript-sdk): prioritize displayName for WebAuthn name attribute

---

.changeset/thin-numbers-hammer.md
packages/javascript-sdk/src/fr-webauthn/fr-webauthn.mock.data.ts
packages/javascript-sdk/src/fr-webauthn/index.ts
packages/javascript-sdk/src/fr-webauthn/interfaces.ts

[SDKS-3843](https://pingidentity.atlassian.net/browse/SDKS-3843)
This adds the optional outcome type to the HiddenValueCallback of JSON to provide `authenticatorAttachment` property.
Did you add a changeset? Yes!

feat(javascript-sdk): allow for json response outcome for webauthn

---

CONTRIBUTING.md
README.md

https://pingidentity.atlassian.net/browse/SDKS-3970
Add and align the contributing documentation with other platforms

chore: contributing-information

---

.changeset/config.json
.changeset/stupid-eagles-cross.md
.github/workflows/publish.yml
package.json
packages/javascript-sdk/package.json
packages/ping-protect/package.json
pnpm-lock.yaml

N/A
This is a publish to fix the versioning problem presented when using `ping-protect`. We are now using the ~^so that any minor will be picked up.
https://pnpm.io/workspaces#publishing-workspace-packages
shows a reference to how this is translated

fix: ping-protect-versioning
